### ISSUE TITLE
Latest CSS not working

### ISSUE THREAD

**Issue by chickenkiller** [sproutcore/Todos-Example#5]
I am using latest git HEAD of sproutcore in `frameworks/sproutcore` subfolder and latest GIT head of master branch of this example.

When trying to load the page, CSS is not applied and I get a ruby backtrace from sc-server:

```
Sass::SyntaxError: Undefined mixin 'background-image'.
    ././tmp/chance/60362d3bd524ac795ae86c281e6666f0.scss:79:in `background-image'
```

The corresponding snippet of scss is here:

``` css
.sc-button {
  @include background-image(linear-gradient(#F9F9F9 1%, #DDD, #F2F2F2, #F7F7F7));
  border: 1px solid #828282;
  color: #000;
  [...]
}
```
